require_relative './classes/author'
require_relative './classes/book'
require_relative './classes/game'
require_relative './classes/item'
require_relative './classes/label'
require_relative './classes/music_album'
require_relative './classes/source'